config/routes.rb
Rails.application.routes.draw do

  post 'photo_likes/:current_user_id/create/:photo_id' => 'photo_likes#create', as: 'create_photo_like'
  post 'album_likes/:current_user_id/create/:album_id' => 'album_likes#create', as: 'create_album_like'

  post 'followships/:current_user_id/create/:user_id' => 'followships#create', as: 'create_followship'
  delete 'followships/:current_user_id/destroy/:user_id' => 'followships#destroy', as: 'delete_followship'

  get 'users/:id/users_i_follow' =>'users#users_i_follow_index', as: 'users_i_follow'
  get 'users/:id/followers' => 'users#followers_index', as: 'followers'
  
  root 'users#index'
  devise_for :users
  get 'users/:id/show' => 'users#show', as: 'users_show'
  
  resources :photos do
    resources :photo_comments
  end

  resources :albums do
    resources :album_comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user
	has_many_attached :pictures
	has_many :album_comments
end

app/models/album_comment.rb
class AlbumComment < ApplicationRecord
	belongs_to :user
	belongs_to :album
end

app/models/album_like.rb
class AlbumLike < ApplicationRecord
	belongs_to :album
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followship.rb
class Followship < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user
	has_many :photo_likes
	has_many :photo_comments
end

app/models/photo_comment.rb
class PhotoComment < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/models/photo_like.rb
class PhotoLike < ApplicationRecord
	belongs_to :photo
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :photos
	has_many :albums
	has_many :photo_likes
	has_many :album_likes
	has_many :photo_comments
	has_many :album_comments

	has_one_attached :avatar
end

app/controllers/album_likes_controller.rb
class AlbumLikesController < ApplicationController
  def create
  	if AlbumLike.find_by(user_id: params[:current_user_id], album_id: params[:album_id])
  		AlbumLike.find_by(user_id: params[:current_user_id], album_id: params[:album_id]).destroy
  		redirect_to users_show_path(Album.find_by(id: params[:album_id]).user_id)
  	else
  		@album_like = AlbumLike.new(:album_id => params[:album_id], :user_id => params[:current_user_id])
  		@album_like.save
  		redirect_to users_show_path(Album.find_by(id: params[:album_id]).user_id)
  	end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.build(album_params)
    if @album.save
      upload_pictures
      redirect_to users_show_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      upload_pictures
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to root_path
  end

  private

  def album_params
    params.require(:album).permit(:title, :desc)
  end

  def upload_pictures
    @album.pictures.attach(uploaded_files) if uploaded_files.present?
  end

  def uploaded_files
    params[:album][:pictures]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :surname, :avatar])
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
     @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build(photo_params)
    
    if @photo.save
      upload_image
      redirect_to users_show_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      upload_image
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_path
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :desc)
  end

  def path_to_the_file(new_file_path)
    string = new_file_path.to_s
    path = "/" + string.split("/")[string.split("/").index("upload")..-1].join("/")
    return path
  end

  def upload_image
    uploaded_file = params[:photo][:image]
    unless uploaded_file.nil?
      new_file_path = Rails.root.join('public', 'upload', 'photos', @photo.id.to_s)
      File.open(new_file_path, 'wb') do |file|
        file.write uploaded_file.read
      end
      @photo.update_attributes(image: path_to_the_file(new_file_path))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def destroy
  end

  def followers_index
  	@followers = []
  	Followship.where(user_to_follow_id: params[:id]).each do |followship|
  		@followers << User.find(followship.follower_user_id)
  	end
  end

  def users_i_follow_index
  	@users_i_follow = []
  	Followship.where(follower_user_id: params[:id]).each do |followship|
  		@users_i_follow << User.find(followship.user_to_follow_id)
  	end
  end
end

app/helpers/album_comments_helper.rb
module AlbumCommentsHelper
end

app/helpers/album_likes_helper.rb
module AlbumLikesHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/photo_comments_helper.rb
module PhotoCommentsHelper
end

app/helpers/photo_likes_helper.rb
module PhotoLikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/album_likes/create.html.erb
<h1>AlbumLikes#create</h1>
<p>Find me in app/views/album_likes/create.html.erb</p>

app/views/albums/_form.html.erb
<%= form_with model: @album, local: true do |f| %>

<% if @album.errors.any? %>
<div class="errors">
	Total errors: <%= @album.errors.count %>
	<ul>
		<% @album.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</div>

<div>
	<%= f.label :description %><br/>
	<%= f.text_area :desc %>
</div>

<div>
	<%= f.label :photos %><br/>
	<%= f.file_field :pictures, multiple: true %>
</div>

<div>
	<%= f.submit %>
</div>
<% end %>

<p><%= link_to 'Back to main', root_path %></p>

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Редактирование альбома</h1>
<%= render 'form' %>

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/new.html.erb
<h1>Добавление нового альбома</h1>
<%= render 'form' %>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/photos/_form.html.erb
<%= form_with model: @photo, local: true do |f| %>

<% if @photo.errors.any? %>
<div class="errors">
	Total errors: <%= @photo.errors.count %>
	<ul>
		<% @photo.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</div>

<div>
	<%= f.label :description %><br/>
	<%= f.text_area :desc %>
</div>

<div>
	<%= f.label :image %><br/>
	<%= f.file_field :image %>
</div>

<div>
	<%= f.submit %>
</div>
<% end %>

<p><%= link_to 'Back to main', root_path %></p>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Редактировать фотографию</h1>
<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<h1>Добавление новой фотографии</h1>
<%= render 'form' %>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/followers_index.html.erb
<h1>My followers:</h1>
<% @followers.each do |follower|  %>
	<%= link_to "#{follower.first_name} #{follower.surname}", users_show_path(follower.id) %><br>
<% end %>
<%= link_to "Back", users_show_path(current_user) %>

app/views/users/index.html.erb
<% if User.all.count > 0 %>
	<% if user_signed_in? %>
		<% @users.each do |user| %>
			<%= "*" * 50 %><br>
			<%= link_to "#{user.first_name} #{user.surname}", users_show_path(user.id) %><br>
			<% if user.avatar.attached? %>
				<%= image_tag user.avatar, size: 100 %>
			<% end %><br>
			<%= "*" * 50 %><br>
		<% end %>
	<% else %>
		<h1>Registrate and log in to see other users profiles!</h1>
		<% @users.each do |user| %>
			<%= "*" * 50 %><br>
			<%= "#{user.first_name} #{user.surname}" %><br>
			<% if user.avatar.attached? %>
				<%= image_tag user.avatar, size: 100 %>
			<% end %><br>
			<%= "*" * 50 %><br>
		<% end %>
	<% end %>
<% else %>
	<h1>There is no users! Be first to registrate!</h1>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>

	<h1><%= "#{@user.first_name} #{@user.surname}" %></h1>
	<% if @user.avatar.attached? %>
		<%= image_tag @user.avatar, size: 100 %>
	<% end %><br>

	<% if Followship.find_by(follower_user_id: current_user.id) %>
		<%= link_to "Users I follow", users_i_follow_path(current_user.id) %>
		<%= Followship.where(follower_user_id: current_user.id).count %>
	<% else %>
		<p>I still don't follow anyone</p>
	<% end %><br>
	<% if Followship.find_by(user_to_follow_id: current_user.id) %>
		<%= link_to "My followers", followers_path(current_user.id) %>
		<%= Followship.where(user_to_follow_id: current_user.id).count %>
	<% else %>
		<p>Still i don't have any follower</p>
	<% end %>

	<div style="text-align: center;">
		<% if @user.photos.count > 0 %>
			<h1>Photos:</h1>
			<% @user.photos.each do |photo| %>
				<%= image_tag photo.image, size: 100 %>
			<% end %>
		<% else %>
			<h1>There is no photo in this profile!</h1>
		<% end %>
	</div>

	<div class="album" style="text-align: center;">
		<% if @user.albums.count > 0 %>
			<h1>Albums:</h1>
			<% @user.albums.each do |album| %>
				<% if album.pictures.attached? %>
					<% album.pictures.each do |picture| %>
   						 <%= image_tag picture, size: 100 %>
					<% end %>
				<% end %><br>
			<% end %>
		<% else %>
			<h1>Create new theme album!</h1>
		<% end %>
	</div>

	<%= link_to "Добавить фотографиЮ", new_photo_path %><br>
	<%= link_to "Добавить тематический альбом", new_album_path %><br>
	<%= link_to "Back to main", root_path %>

<% else %>


	<h1><%= "#{@user.first_name} #{@user.surname}" %></h1>
	<% if @user.avatar.attached? %>
		<%= image_tag @user.avatar, size: 100 %>
	<% end %><br>

	<% if Followship.find_by(follower_user_id: current_user.id, user_to_follow_id: @user.id) %>
		<%= link_to "Unfollow", delete_followship_path(current_user.id, @user.id), method: :delete%>
	<% else %>
		<%= link_to "Follow", create_followship_path(current_user.id, @user.id), method: :post %>
	<% end %>

	<div style="text-align: center;">
		<% if @user.photos.count > 0 %>
			<h1>Photos:</h1>
			<% @user.photos.each do |photo| %>
				<%= image_tag photo.image, size: 100 %><br>
				<%= link_to 'Like', create_photo_like_path(current_user.id, photo.id), method: :post %>
				<%= PhotoLike.all.where(photo_id: photo.id).count %><br>
				<% if PhotoComment.all.count > 0 %>
					<% PhotoComment.all.where(photo_id: photo.id).each do |comment| %>
						<%= comment.body %> said: <%= comment.user.surname %> | <%= link_to "Delete the comment", photo_photo_comment_path(photo.id, comment.id), method: :delete %><br>
					<% end %>
				<% else %>
					<p>There is still no comments! Be first!</p>
				<% end %>
				<%= render './photo_comments/form.html.erb', photo: photo %>
			<% end %>
		<% else %>
			<h1>There is no photo in this profile!</h1>
		<% end %>
	</div>

	<div class="album" style="text-align: center;">
		<% if @user.albums.count > 0 %>
			<h1>Albums:</h1>
			<% @user.albums.each do |album| %>
				<% if album.pictures.attached? %>
					<% album.pictures.each do |picture| %>
   						 <%= image_tag picture, size: 100 %>
					<% end %>
				<% end %><br>
				<%= link_to 'Like', create_album_like_path(current_user.id, album.id), method: :post%>
				<%= AlbumLike.all.where(album_id: album.id).count %><br>
				<% if AlbumComment.all.count > 0 %>
					<% AlbumComment.all.where(album_id: album.id).each do |comment| %>
						<%= comment.body %> said: <%= comment.user.surname %> | <%= link_to "Delete the comment", album_album_comment_path(album.id, comment.id), method: :delete %><br>
					<% end %>
				<% else %>
					<p>There is still no comments! Be first!</p>
				<% end %>
				<%= render './album_comments/form.html.erb', album: album %>
			<% end %>
		<% else %>
			<h1>The user still didn't create an album!</h1>
		<% end %>
	</div>
	
	<!-- Это код карусели и он в работе -->
	<% if @user.albums.count > 0 %>
		<% @user.albums.each do |album| %>
			<% if album.pictures.attached? %>
				<div id="myCarousel" class="carousel slide" data-ride="carousel">

					<ol class="carousel-indicators">
						<% album.pictures.each_with_index do |picture, n| %>
							<li data-target="#myCarousel" data-slide-to="#{n}" class="<%= n == 0 ? 'active' : '' %>">
							</li>
						<% end %>
					</ol>
	
					<div class="carousel-inner" role="listbox">
						<div class="item active">
							<%= image_tag album.pictures.first, size: 100 %>
						</div>
						<% album.pictures.drop(1).each do |pic| %>
							<div class="item">
								<%= image_tag pic, size: 100 %>
							</div>
						<% end %>
					</div>

					<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			<% end %>
		<% end %>
	<% else %>
		<h1>The user still didn't create an album!</h1>
	<% end %>

	<%= link_to "Back to main", root_path %>

<% end %>

app/views/users/users_i_follow_index.html.erb
<h1>Users i follow:</h1>
<% @users_i_follow.each do |user_i_follow|  %>
	<%= link_to "#{user_i_follow.first_name} #{user_i_follow.surname}", users_show_path(user_i_follow.id) %><br>
<% end %>

<%= link_to "Back", users_show_path(current_user) %>